# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Build apk"
  lane :build_apk do
    sh "flutter pub get"
    sh "flutter build apk --release"
  end

  desc "Build aab"
  lane :build_aab do
    sh "flutter pub get"
    sh "flutter build appbundle --release"
  end

  desc "Submit a new internal build to Google Play"
  lane :upload_to_internal_track do
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft', # this is temporary because my app is not fully created on google play
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: "/Users/sanniprasad/Documents/CICD\ workshop\ files/playstore-api-5686676658611279098-871674-865ef056a479.json",
      )
  end
end
